apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pbyI6eyJ1c2VybmFtZSI6InNoYWVraGhhc2FuIiwicGFzc3dvcmQiOiIxOGVkYzdiZi01ODA5LTRkNTUtOWNhNS1mMTRkYjk5YmE5Y2IiLCJlbWFpbCI6Im51bGwiLCJhdXRoIjoiYzJoaFpXdG9hR0Z6WVc0Nk1UaGxaR00zWW1ZdE5UZ3dPUzAwWkRVMUxUbGpZVFV0WmpFMFpHSTVPV0poT1dOaSJ9fX0=
kind: Secret
metadata:
  name: regcred-secret
  namespace: ultra-edge
type: kubernetes.io/dockerconfigjson