apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-app
  name: demo-app
#  namespace: ultra-edge
spec:
  ports:
    - name: http-rest
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: http-metrics
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: demo-app
  type: ClusterIP